sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '6'
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: F+d6ib3BGdF5hSFiMqH38F+obO1vNAD9RemHRrypR5cipRyA3iU9eOWSb31C/ZiSaxoYaPI654WYosHJZmX11yI8HrtHxY9G9aKuJtpbLO+jRaMKlj1E/CbOongL89Wc+hUbsrBdphxlo9jqPppvdv3PooxJ2QSR3x399W8lRLFNCyknqJ+q45mNtH96w9e6BMOnvArcetDeAeD0/Qj3NUmY/Z4uVOZMXONOKzOky4DJHZ3ybBXD6w0M1V4H8KcDPAtNRQKUOJW7a4eWZc7Up07St78BGzFpPpyZx1AkUStGqInh66RWhpYUVXyu+S7DP/aKJIZRZqSRZfobDc5il8OqlWrfKr5j/Sj8QHAZrmiYKDYomIC9PiQMqftr9hF4oy8C9juuGx+46VfQlk6+XqNbdAgMy85YVcbCZhzcPB3cRJEe+GQwbflkRW3SG9ENWuXQBQkPo9krF4oRLkQXuHwyV/IemjKhyx/P2OoDRwfNuazkUGDHL1/y4R6f25UhcXe8LVur2gtyiiMOCTkwEyEGSPzdX37JYbpcLosGCMjKImP+cjl8nvH+erCrBM5M07PdRBzDQb1PE7wfHgR3MMJf+40Q+WRziOv+hzy0nd0vXp3aXLbPm5rPg8X3O0ezvxNQASeCQu3zJXKCCJJTEYS67hHNbWxsHRx7Zb/RDpE=
