language: node_js
node_js:
- node
script:
- npm run lint
- npm run build
- npm run test
notifications:
  slack:
    secure: uTSgpbw6Q4ZVUh89DpZ8KQTeOs+UxD+Oo5WZUVsKQbaR/L4jMTI+ozzT+uBQYRgpVfM8KfKydX1VDV+iaMRzr4ASkFfDNGgxBetiqZSepSk/4LQ+fzqz4NEbFVksehv44QKsJ/foVYXN1J1GEhynw80pJtThQsgrUSPHGHCVManT3nIeXSPQJJumD2QiJqPRtDscHzMq6GFerp1ZXwGbn3HBbgHjKgxPWZgGEXbak92aMm6CBRrAiU9uxLmpbbm4GsUUsRLiPdJ+jyBC7ij9iOIKUSXvqdYctXKxzqnDyl/Ay1cA8bG1FK7b+Fj23Y3ziLUklVJiTWNtGEj/oz359J3pAfh2w9SToI/QB8OydssgiHR+CfEESlsoQ8S3liJm0L/Cm8yQDuoFbjkuHkpVndn/QUqJ9UAceSMYBr06uBDAfr3hALs4DS9I2ObVuELsIrd+H+ISxubJJ8FOFUxBXqKgrxXBae0fXLvKCJvzfzAw3TOfdcqF1JzXpTGgOpmdI23QMBO2ZyeauJuvgy8kkgOj3z7wqvLhSuRf4SI56SZf4ynV5kZbzxjTZR2Pm7YpxdBLrpzqt+dnpC0ucOFa8OHL8xZ0NBTlkvec53IwXDn9SmiuDMq15oMbDs/cquI9F+Tf0+kQbtnKiGZY5PBK4gqFNF+1tNVaSyWIJDNNsrw=
