language: node_js
node_js:
  - node
script:
  - npm run lint
  - npm run build
  - npm run test
notifications:
  slack:
    secure: 1hEfazftlMONwDXBl9SGap30TZ6zYytCmnYHZq7Xd91Ety5jghc/jxK+vSN1K6BvYbmKqo3sncGHSaZGpDfNYZdmgZBWRXjFRArB5sXbCuFUuHZ6oeG13MYmAAaCQ7lBCxLutd1R3CkbItQScAGqHOpqHWlfzTbmnuPKwQeRhoRoW6tNoKDqoYhyj0wRNbbauTUH60uQ5pN8+GIR9izI40V5Atv9I1nvT/kXVX8hpHzz9H+g+9zfSUIVUJmtzqGeMyVoGAY525Ra+quJi57hxydhl+jDmTEox0YTC1+IWhSypgY5Jst0yinWtGHSUEobrbXHgGKbgcEmTO8kJecRgU2rZmFSbch28uPEp8oFoZlRsV8msabMs+xK/9JZnkH6G6JthKTubvEVI/9sCYJtYc1wUNfYssQZ1GLw2AimPhGmcd3F3cbBYBfN1CnCGsUc/TCQw6eeONzktgzS9d7CSR82DiueGdrG7ungRWXfqv09s29HcSBByT9cTYAdCYI+jF1bGtbvK4XCjahxI8eRUI7DPEc12f5kSBICMsMcKfUeyYYYiS+oye7mJh3Yd/oJgVmrrti7APWB3c2ghjrCi+B3/Frkb4bwbizzqmG4LQRomRwrnjYm1e68Ak/wXXg4C67yWq2ArOo0lNJ7iAfvc75U3Mnol3u+QwEyo2eerWI=
